#!/bin/sh
# tests/check_headers.sh — Static header/symbol consistency suite for
# libsolcompat. Catches the three failure modes that have repeatedly
# bitten the sst-build-pipeline cross-build:
#
#   1. Link smoke test
#      Generate a single .c that includes every solcompat/*.h header
#      and takes (void *)&fn for every declared function. Compile + link
#      against libsolcompat.a + the sysroot. Catches header decls that
#      have no backing definition (e.g. iswblank), and macro redirects
#      that resolve to a non-existent target.
#
#   2. Header cleanliness
#      For every override/*.h, parse-only compile a tiny TU under -x c
#      and -x c++. Also exercises:
#        - assert.h re-includability with NDEBUG toggling
#        - C++ std::snprintf via <cstdio> (catches #define snprintf foo
#          collisions in C-mode override headers)
#
#   3. Critical bare symbols
#      Hardcoded list of "Solaris 7 libc lacks this; libsolcompat must
#      own the bare name". Verified against `nm --defined-only` output
#      from libsolcompat.a. The list grows whenever a cross-build link
#      failure exposes a new gap.
#
# Invoked from `make check`. Inherits CC, NM, CFLAGS, CPPFLAGS from the
# Makefile so the same toolchain and sysroot used to build the library
# is used to test it.

set -eu

CC=${CC:?CC must be set}
NM=${NM:-nm}
CFLAGS=${CFLAGS:-}
CPPFLAGS=${CPPFLAGS:-}
LIB=${LIB:-libsolcompat.a}

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
GEN="$ROOT/tests/gen"
rm -rf "$GEN"
mkdir -p "$GEN"

if [ ! -f "$ROOT/$LIB" ]; then
    echo "ERROR: $LIB not found in $ROOT — run 'make' first" >&2
    exit 1
fi

INC="$ROOT/include"
OVERRIDE_INC="$INC/override"

# -isystem so override/*.h go in front of the sysroot include path,
# which is what the production sst-build-pipeline cross-build does.
TEST_CPPFLAGS="-isystem $OVERRIDE_INC -I$INC $CPPFLAGS"
TEST_CFLAGS="$CFLAGS"

PASS=0
FAIL=0

ok()  { PASS=$((PASS + 1)); printf '  ok    %s\n' "$1"; }
bad() { FAIL=$((FAIL + 1)); printf '  FAIL  %s\n' "$1"; }

# ----------------------------------------------------------------------
# Heuristic function-name extractor.
#
# Picks up top-level function declarations of the form
#     <type...> <name>(<args>);
# where the line begins at column 1 (no leading whitespace) and is not
# a comment, preprocessor directive, typedef, or struct/union/enum.
# The function name is the last C identifier on the line before '('.
# Multi-line declarations work because we only look at the line that
# contains the '(' — continuation lines are indented and skipped.
# ----------------------------------------------------------------------
extract_decls() {
    awk '
        /^#/                  { next }
        /^[ \t]*\/\*/         { next }
        /^[ \t]*\*/           { next }
        /^[ \t]*$/            { next }
        /^[ \t]/              { next }
        /^typedef/            { next }
        /^struct/             { next }
        /^union/              { next }
        /^enum/               { next }
        /^static/             { next }
        /^extern[ \t]+"C"/    { next }
        /[a-zA-Z_][a-zA-Z_0-9]*[ \t]*\(/ {
            line = $0
            sub("[ \t]*\\(.*$", "", line)
            if (match(line, /[a-zA-Z_][a-zA-Z_0-9]*$/)) {
                name = substr(line, RSTART, RLENGTH)
                if (name !~ /^(if|while|for|switch|return|sizeof|defined|static_assert|extern|inline)$/) {
                    print name
                }
            }
        }
    ' "$1"
}

# ----------------------------------------------------------------------
# Test 1 — Link smoke test
# ----------------------------------------------------------------------
echo "==> [1/3] Link smoke test"

GEN_C="$GEN/link_smoke.c"
{
    cat <<'PREAMBLE'
/* AUTO-GENERATED by tests/check_headers.sh — do not edit.
 *
 * One reference per declared function in include/solcompat/*.h and
 * include/override/*.h. Linking this file against libsolcompat.a + the
 * sysroot must succeed; any unresolved reference is a header that
 * promises a function nobody defines.
 */
#include <stddef.h>
#include <sys/types.h>
PREAMBLE
    # Pull in every override header by its bare system name. -isystem
    # makes <foo.h> resolve to override/foo.h, which #include_next's
    # the real Solaris header, which is what production builds see.
    for header_path in "$OVERRIDE_INC"/*.h; do
        [ -e "$header_path" ] || continue
        header_base=$(basename "$header_path")
        echo "#include <$header_base>"
    done
    for header_path in "$INC"/solcompat/*.h; do
        header_base=$(basename "$header_path")
        case "$header_base" in
            compat_types.h|solcompat.h) continue ;;
        esac
        echo "#include <solcompat/$header_base>"
    done
    cat <<'BODY'

void link_smoke_use(void *p);
void link_smoke_use(void *p) { (void)p; }

int main(void) {
BODY
    {
        for header_path in "$INC"/solcompat/*.h; do
            header_base=$(basename "$header_path")
            case "$header_base" in
                compat_types.h|solcompat.h) continue ;;
            esac
            extract_decls "$header_path"
        done
        for header_path in "$OVERRIDE_INC"/*.h; do
            extract_decls "$header_path"
        done
    } | sort -u | while read -r function_name; do
        [ -n "$function_name" ] || continue
        printf '    link_smoke_use((void *)&%s);\n' "$function_name"
    done
    cat <<'TAIL'
    return 0;
}
TAIL
} > "$GEN_C"

reference_count=$(grep -c 'link_smoke_use((void' "$GEN_C" || true)
printf '  generated %s symbol references\n' "$reference_count"

LINK_BIN="$GEN/link_smoke"
LINK_LOG="$GEN/link_smoke.log"

# shellcheck disable=SC2086
if $CC $TEST_CFLAGS $TEST_CPPFLAGS \
        -o "$LINK_BIN" \
        "$GEN_C" \
        "$ROOT/$LIB" \
        -lm -lsocket -lnsl -lresolv -lrt -ldl -lpthread \
        > "$LINK_LOG" 2>&1; then
    ok "link_smoke compiled and linked"
else
    bad "link_smoke failed"
    sed 's/^/      /' "$LINK_LOG"
fi

# ----------------------------------------------------------------------
# Test 2 — Header cleanliness
# ----------------------------------------------------------------------
echo "==> [2/3] Header cleanliness"

# 2a. Per-header parse under -x c and -x c++.
for header_path in "$OVERRIDE_INC"/*.h "$OVERRIDE_INC"/cmath "$OVERRIDE_INC"/cstdlib; do
    [ -e "$header_path" ] || continue
    header_base=$(basename "$header_path")

    # cmath/cstdlib have no .h extension and #include directly with
    # angle brackets. They are also C++-only.
    cpp_only=0
    case "$header_base" in
        cmath|cstdlib) cpp_only=1 ;;
    esac

    stub_c="$GEN/stub_$(printf '%s' "$header_base" | tr -c 'a-zA-Z0-9_' '_').c"
    {
        echo "#include <$header_base>"
        echo "int main(void) { return 0; }"
    } > "$stub_c"

    if [ "$cpp_only" -eq 0 ]; then
        log="$stub_c.c.log"
        # shellcheck disable=SC2086
        if $CC $TEST_CFLAGS $TEST_CPPFLAGS -fsyntax-only -x c "$stub_c" \
                > "$log" 2>&1; then
            ok "C parse: override/$header_base"
        else
            bad "C parse: override/$header_base"
            sed 's/^/      /' "$log"
        fi
    fi

    log="$stub_c.cxx.log"
    # shellcheck disable=SC2086
    if $CC $TEST_CFLAGS $TEST_CPPFLAGS -fsyntax-only -x c++ "$stub_c" \
            > "$log" 2>&1; then
        ok "C++ parse: override/$header_base"
    else
        bad "C++ parse: override/$header_base"
        sed 's/^/      /' "$log"
    fi
done

# 2b. assert.h re-includability — C requires assert() to be redefinable
# whenever NDEBUG flips. A leftover include guard breaks this; commit
# 1dfe8d3 was the fix.
ASSERT_C="$GEN/assert_reinclude.c"
cat > "$ASSERT_C" <<'EOF'
#include <assert.h>
#define NDEBUG
#include <assert.h>
#undef NDEBUG
#include <assert.h>
int main(void) {
    assert(1 == 1);
    return 0;
}
EOF
log="$GEN/assert_reinclude.log"
# shellcheck disable=SC2086
if $CC $TEST_CFLAGS $TEST_CPPFLAGS -fsyntax-only -x c "$ASSERT_C" \
        > "$log" 2>&1; then
    ok "assert.h is re-includable"
else
    bad "assert.h is not re-includable"
    sed 's/^/      /' "$log"
fi

# 2c. C++ std::snprintf must compile and parse. A C-mode override that
# does `#define snprintf solcompat_snprintf` corrupts this into
# `std::solcompat_snprintf`, breaking every C++ package.
CXX_SNPRINTF="$GEN/cxx_snprintf.cc"
cat > "$CXX_SNPRINTF" <<'EOF'
#include <cstdio>
#include <cstddef>
int main(void) {
    char buffer[16];
    int written = std::snprintf(buffer, sizeof buffer, "%d", 42);
    return written > 0 ? 0 : 1;
}
EOF
log="$GEN/cxx_snprintf.log"
# shellcheck disable=SC2086
if $CC $TEST_CFLAGS $TEST_CPPFLAGS -fsyntax-only -x c++ "$CXX_SNPRINTF" \
        > "$log" 2>&1; then
    ok "std::snprintf parses in C++"
else
    bad "std::snprintf does not parse in C++"
    sed 's/^/      /' "$log"
fi

# ----------------------------------------------------------------------
# Test 3 — Critical bare symbols
# ----------------------------------------------------------------------
echo "==> [3/3] Critical bare symbols"

# Solaris 7 libc lacks each of these and there is no override-header
# path that always wraps the call site (gnulib's error.c, wordwrap.c,
# regex.c, etc. emit bare references). libsolcompat must own each as
# a global text symbol or the cross-build link breaks.
#
# This list grows when a new "undefined reference to <fn>" surfaces in
# cross-compile output. Past additions:
#   - strerror_r  (commit 60d4bb7, gnulib error.c)
#   - iswblank    (commit 4ea0650, gnulib wordwrap.c, gdbm tooling)
CRITICAL_BARE_SYMS="
strerror_r
iswblank
"

DEFINED_LIST="$GEN/defined_symbols.txt"
$NM --defined-only "$ROOT/$LIB" 2>/dev/null \
    | awk '$2 == "T" || $2 == "W" { print $3 }' \
    | sort -u > "$DEFINED_LIST"

for symbol in $CRITICAL_BARE_SYMS; do
    if grep -qx "$symbol" "$DEFINED_LIST"; then
        ok "libsolcompat exports bare $symbol"
    else
        bad "libsolcompat is missing bare $symbol"
    fi
done

# ----------------------------------------------------------------------
# Summary
# ----------------------------------------------------------------------
echo
printf '==> %d passed, %d failed\n' "$PASS" "$FAIL"
[ "$FAIL" -eq 0 ]
